// src/components/letterTile.svelte
<!--
    components/letterTile.svelte
-->

<script lang="ts">
    import type { TileData, TileHighlight } from "$lib/game/types";

    interface Props {
        tile: TileData;
        highlight?: TileHighlight;
    }

    let { tile, highlight = "none" }: Props = $props();

    // Determine background color based on highlight
    const bgColor = $derived(() => {
        switch (highlight) {
            case "horizontal":
                return "bg-blue-300 text-blue-900";
            case "vertical":
                return "bg-orange-300 text-orange-900";
            case "intersection":
                return "bg-purple-300 text-purple-900";
            case "opponent-owned":
                return "bg-red-300 text-red-900";
            default:
                return "bg-orange-200 text-black";
        }
    });
</script>

<div
    id="letterTile"
    class="aspect-square rounded-xl border-4 {bgColor()} flex flex-col items-center justify-center w-10 h-10 p-8"
>
    <h class="text-4xl font-bold">{tile.letter}</h>
    <span class="flex flex-row gap-1 items-center">
        <h class="text-md font-semibold">{tile.baseScore}</h>
        <p class="text-sm">x</p>
        <h class="text-md font-semibold">{tile.multiplier}</h>
    </span>
</div>

// src/components/letterTile.tsx
// components/LetterTile.tsx

import type { Tile } from "../utils/letterBag";

interface LetterTileProps {
  tile: Tile;
  onDragStart?: (tile: Tile) => void;
  draggable?: boolean;
  highlight?: 'horizontal' | 'vertical' | 'both' | null;
}

export default function LetterTile({ tile, onDragStart, draggable = false, highlight = null }: LetterTileProps) {
  const handleDragStart = (e: React.DragEvent) => {
    if (onDragStart) {
      onDragStart(tile);
      e.dataTransfer.effectAllowed = 'move';
      e.dataTransfer.setData('text/plain', tile.id);
    }
  };

  // Determine letter color based on highlight
  const getLetterColor = () => {
    if (highlight === 'horizontal') return 'text-blue-600';
    if (highlight === 'vertical') return 'text-orange-600';
    if (highlight === 'both') return 'text-purple-600';
    return 'text-neutral-900';
  };

  return (
    <div
      className="rounded-xl border lg:border-4 border-black/20 bg-amber-100 w-full h-full flex flex-col items-center justify-center relative cursor-grab active:cursor-grabbing transition-all duration-100"
      draggable={draggable}
      onDragStart={handleDragStart}
    >
      <div className={`absolute top-1 lg:top-0.5 text-lg lg:text-3xl font-semibold leading-none ${getLetterColor()}`}>{tile.letter === '_' ? '' : tile.letter}</div>
      <div className="absolute bottom-0.5 right-1 text-xs lg:text-sm font-bold">
        {tile.score}
      </div>
      {tile.multiplier > 1 && (
        <div className="absolute top-0.5 right-1 text-xs lg:text-sm font-bold text-red-600 bg-red-100 px-0.5 rounded">
          x{tile.multiplier}
        </div>
      )}
    </div>
  );
}
