// src/components/wordGrid.svelte
<!--
    components/wordGrid.svelte
-->

<script lang="ts">
    import LetterSlot from "./letterSlot.svelte";
    import { gameState, BOARD_CONFIG } from "$lib/game/state.svelte";
</script>

<div class="grid grid-cols-{BOARD_CONFIG.COLS} grid-rows-{BOARD_CONFIG.ROWS} gap-px w-fit h-fit">
    {#each gameState.board as slot, index}
        <LetterSlot {index} tile={slot.heldLetterTile} />
    {/each}
</div>

// src/components/wordGrid.tsx
// components/WordGrid.tsx

import type { Tile } from "../utils/letterBag";
import LetterSlot from "./letterSlot";

const GRID_COLS = 7;
const GRID_ROWS = 6;

interface WordGridProps {
  tiles: (Tile | null)[];
  onDrop: (index: number) => void;
}

export default function WordGrid({ tiles, onDrop }: WordGridProps) {
  return (
    <div className={`grid gap-0.5 grid-cols-${GRID_COLS} grid-rows-${GRID_ROWS}`}>
      {tiles.map((tile, i) => (
        <LetterSlot
          key={`slot-${i}`}
          index={i}
          tile={tile}
          onDrop={onDrop}
          allowDrop={true}
        />
      ))}
    </div>
  );
}
